name: ChalixShop/OldVersion
main: GuiShop\Main
version: 2.0Beta
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: VMPE Developement Team
description: ShopUI for servers!
commands:
 shop:
  description: Opens a shop ui to buy and sell
